export const TYPES = {
  databases: {
    CREATE_DATABASE: 'CREATE_DATABASE',
    CREATE_DATABASE_SUCCESS: 'CREATE_DATABASE_SUCCESS',
    UPDATE_DATABASE_SUCCESS: 'UPDATE_DATABASE_SUCCESS',
    LOAD_DATABASES_SUCCESS: 'LOAD_DATABASES_SUCCESS'
  },
  ajax: {
    BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
    AJAX_CALL_ERROR: 'AJAX_CALL_ERROR'
  }
};
